-- V4__Seed_lookup_tables.sql

INSERT INTO user_roles (code, name)
VALUES ('USER', 'Normal user'),
       ('ADMIN', 'Administrator'),
       ('MODERATOR', 'Moderator') ON CONFLICT (code) DO NOTHING;

INSERT INTO moderation_statuses (code, name, description)
VALUES ('PENDING', 'Pending', 'Content pending manual review'),
       ('APPROVED', 'Approved', 'Content formally approved after review'),
       ('REJECTED', 'Rejected', 'Content removed by moderators after review') ON CONFLICT (code) DO NOTHING;

-- Country codes and names - ISO-3166 (alfa-2)
INSERT INTO countries (code, name)
SELECT code, name FROM (
  VALUES
    ('AF', 'Afganistán'),
    ('AL', 'Albania'),
    ('DZ', 'Argelia'),
    ('AS', 'Samoa Americana'),
    ('AD', 'Andorra'),
    ('AO', 'Angola'),
    ('AI', 'Anguila'),
    ('AQ', 'Antártida'),
    ('AG', 'Antigua y Barbuda'),
    ('AR', 'Argentina'),
    ('AM', 'Armenia'),
    ('AW', 'Aruba'),
    ('AU', 'Australia'),
    ('AT', 'Austria'),
    ('AZ', 'Azerbaiyán'),
    ('BS', 'Bahamas'),
    ('BH', 'Baréin'),
    ('BD', 'Bangladés'),
    ('BB', 'Barbados'),
    ('BY', 'Bielorrusia'),
    ('BE', 'Bélgica'),
    ('BZ', 'Belice'),
    ('BJ', 'Benín'),
    ('BM', 'Bermudas'),
    ('BT', 'Bután'),
    ('BO', 'Bolivia (Estado Plurinacional de)'),
    ('BQ', 'Bonaire, San Eustaquio y Saba'),
    ('BA', 'Bosnia y Herzegovina'),
    ('BW', 'Botsuana'),
    ('BV', 'Isla Bouvet'),
    ('BR', 'Brasil'),
    ('IO', 'Territorio Británico del Océano Índico'),
    ('BN', 'Brunéi Darussalam'),
    ('BG', 'Bulgaria'),
    ('BF', 'Burkina Faso'),
    ('BI', 'Burundi'),
    ('CV', 'Cabo Verde'),
    ('KH', 'Camboya'),
    ('CM', 'Camerún'),
    ('CA', 'Canadá'),
    ('KY', 'Islas Caimán'),
    ('CF', 'República Centroafricana'),
    ('TD', 'Chad'),
    ('CL', 'Chile'),
    ('CN', 'China'),
    ('CX', 'Isla de Navidad'),
    ('CC', 'Islas Cocos (Keeling)'),
    ('CO', 'Colombia'),
    ('KM', 'Comoras'),
    ('CG', 'Congo'),
    ('CD', 'Congo (la República Democrática del)'),
    ('CK', 'Islas Cook'),
    ('CR', 'Costa Rica'),
    ('CI', 'Côte d''Ivoire'),
    ('HR', 'Croacia'),
    ('CU', 'Cuba'),
    ('CW', 'Curazao'),
    ('CY', 'Chipre'),
    ('CZ', 'Chequia'),
    ('DK', 'Dinamarca'),
    ('DJ', 'Yibuti'),
    ('DM', 'Dominica'),
    ('DO', 'República Dominicana'),
    ('EC', 'Ecuador'),
    ('EG', 'Egipto'),
    ('SV', 'El Salvador'),
    ('GQ', 'Guinea Ecuatorial'),
    ('ER', 'Eritrea'),
    ('EE', 'Estonia'),
    ('SZ', 'Esuatini'),
    ('ET', 'Etiopía'),
    ('FK', 'Islas Malvinas (Falkland Islands)'),
    ('FO', 'Islas Feroe'),
    ('FJ', 'Fiyi'),
    ('FI', 'Finlandia'),
    ('FR', 'Francia'),
    ('GF', 'Guayana Francesa'),
    ('PF', 'Polinesia Francesa'),
    ('TF', 'Tierras Australes Francesas'),
    ('GA', 'Gabón'),
    ('GM', 'Gambia'),
    ('GE', 'Georgia'),
    ('DE', 'Alemania'),
    ('GH', 'Ghana'),
    ('GI', 'Gibraltar'),
    ('GR', 'Grecia'),
    ('GL', 'Groenlandia'),
    ('GD', 'Granada'),
    ('GP', 'Guadalupe'),
    ('GU', 'Guam'),
    ('GT', 'Guatemala'),
    ('GG', 'Guernsey'),
    ('GN', 'Guinea'),
    ('GW', 'Guinea-Bisáu'),
    ('GY', 'Guyana'),
    ('HT', 'Haití'),
    ('HM', 'Islas Heard y McDonald'),
    ('VA', 'Santa Sede (Ciudad del Vaticano)'),
    ('HN', 'Honduras'),
    ('HK', 'Hong Kong'),
    ('HU', 'Hungría'),
    ('IS', 'Islandia'),
    ('IN', 'India'),
    ('ID', 'Indonesia'),
    ('IR', 'Irán (República Islámica de)'),
    ('IQ', 'Irak'),
    ('IE', 'Irlanda'),
    ('IM', 'Isla de Man'),
    ('IL', 'Israel'),
    ('IT', 'Italia'),
    ('JM', 'Jamaica'),
    ('JP', 'Japón'),
    ('JE', 'Jersey'),
    ('JO', 'Jordania'),
    ('KZ', 'Kazajistán'),
    ('KE', 'Kenia'),
    ('KI', 'Kiribati'),
    ('KP', 'Corea (la República Popular Democrática de)'),
    ('KR', 'Corea (la República de)'),
    ('KW', 'Kuwait'),
    ('KG', 'Kirguistán'),
    ('LA', 'Lao (República Democrática Popular)'),
    ('LV', 'Letonia'),
    ('LB', 'Líbano'),
    ('LS', 'Lesoto'),
    ('LR', 'Liberia'),
    ('LY', 'Libia'),
    ('LI', 'Liechtenstein'),
    ('LT', 'Lituania'),
    ('LU', 'Luxemburgo'),
    ('MO', 'Macao'),
    ('MG', 'Madagascar'),
    ('MW', 'Malaui'),
    ('MY', 'Malasia'),
    ('MV', 'Maldivas'),
    ('ML', 'Malí'),
    ('MT', 'Malta'),
    ('MH', 'Islas Marshall'),
    ('MQ', 'Martinica'),
    ('MR', 'Mauritania'),
    ('MU', 'Mauricio'),
    ('YT', 'Mayotte'),
    ('MX', 'México'),
    ('FM', 'Micronesia (Estados Federados de)'),
    ('MD', 'Moldavia (la República de)'),
    ('MC', 'Mónaco'),
    ('MN', 'Mongolia'),
    ('ME', 'Montenegro'),
    ('MS', 'Montserrat'),
    ('MA', 'Marruecos'),
    ('MZ', 'Mozambique'),
    ('MM', 'Myanmar'),
    ('NA', 'Namibia'),
    ('NR', 'Nauru'),
    ('NP', 'Nepal'),
    ('NL', 'Países Bajos'),
    ('NC', 'Nueva Caledonia'),
    ('NZ', 'Nueva Zelanda'),
    ('NI', 'Nicaragua'),
    ('NE', 'Níger'),
    ('NG', 'Nigeria'),
    ('NU', 'Niue'),
    ('NF', 'Isla Norfolk'),
    ('MK', 'Macedonia del Norte'),
    ('MP', 'Islas Marianas del Norte'),
    ('NO', 'Noruega'),
    ('OM', 'Omán'),
    ('PK', 'Pakistán'),
    ('PW', 'Palaos'),
    ('PS', 'Palestina, Estado de'),
    ('PA', 'Panamá'),
    ('PG', 'Papúa Nueva Guinea'),
    ('PY', 'Paraguay'),
    ('PE', 'Perú'),
    ('PH', 'Filipinas'),
    ('PN', 'Islas Pitcairn'),
    ('PL', 'Polonia'),
    ('PT', 'Portugal'),
    ('PR', 'Puerto Rico'),
    ('QA', 'Catar'),
    ('RE', 'Reunión'),
    ('RO', 'Rumania'),
    ('RU', 'Rusia (Federación de)'),
    ('RW', 'Ruanda'),
    ('BL', 'San Bartolomé'),
    ('SH', 'Santa Elena, Ascensión y Tristán de Acuña'),
    ('KN', 'San Cristóbal y Nieves'),
    ('LC', 'Santa Lucía'),
    ('MF', 'San Martín (parte francesa)'),
    ('PM', 'San Pedro y Miquelón'),
    ('VC', 'San Vicente y las Granadinas'),
    ('WS', 'Samoa'),
    ('SM', 'San Marino'),
    ('ST', 'Santo Tomé y Príncipe'),
    ('SA', 'Arabia Saudita'),
    ('SN', 'Senegal'),
    ('RS', 'Serbia'),
    ('SC', 'Seychelles'),
    ('SL', 'Sierra Leona'),
    ('SG', 'Singapur'),
    ('SX', 'San Martín (parte neerlandesa)'),
    ('SK', 'Eslovaquia'),
    ('SI', 'Eslovenia'),
    ('SB', 'Islas Salomón'),
    ('SO', 'Somalia'),
    ('ZA', 'Sudáfrica'),
    ('GS', 'Islas Georgias del Sur y Sandwich del Sur'),
    ('SS', 'Sudán del Sur'),
    ('ES', 'España'),
    ('LK', 'Sri Lanka'),
    ('SD', 'Sudán'),
    ('SR', 'Surinam'),
    ('SJ', 'Svalbard y Jan Mayen'),
    ('SE', 'Suecia'),
    ('CH', 'Suiza'),
    ('SY', 'Siria (República Árabe)'),
    ('TW', 'Taiwán (Provincia de China)'),
    ('TJ', 'Tayikistán'),
    ('TZ', 'Tanzania (República Unida de)'),
    ('TH', 'Tailandia'),
    ('TL', 'Timor Oriental'),
    ('TG', 'Togo'),
    ('TK', 'Tokelau'),
    ('TO', 'Tonga'),
    ('TT', 'Trinidad y Tobago'),
    ('TN', 'Túnez'),
    ('TR', 'Turquía'),
    ('TM', 'Turkmenistán'),
    ('TC', 'Islas Turcas y Caicos'),
    ('TV', 'Tuvalu'),
    ('UG', 'Uganda'),
    ('UA', 'Ucrania'),
    ('AE', 'Emiratos Árabes Unidos'),
    ('GB', 'Reino Unido de Gran Bretaña e Irlanda del Norte'),
    ('UM', 'Islas Ultramarinas Menores de Estados Unidos'),
    ('US', 'Estados Unidos de América'),
    ('UY', 'Uruguay'),
    ('UZ', 'Uzbekistán'),
    ('VU', 'Vanuatu'),
    ('VE', 'Venezuela (República Bolivariana de)'),
    ('VN', 'Viet Nam'),
    ('VG', 'Islas Vírgenes (Británicas)'),
    ('VI', 'Islas Vírgenes (EE.UU.)'),
    ('WF', 'Wallis y Futuna'),
    ('EH', 'Sahara Occidental'),
    ('YE', 'Yemen'),
    ('ZM', 'Zambia'),
    ('ZW', 'Zimbabue'),
    ('AX', 'Islas Åland')
) AS vals(code, name)
WHERE NOT EXISTS (
    SELECT 1 FROM countries WHERE code = vals.code
);