name: Build and Deploy Spring Boot API to EC2 instance

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPO }}:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPO }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPO }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPO }}:buildcache,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

#      - name: Copy docker-compose.yml to EC2
#        uses: appleboy/scp-action@master
#        with:
#          host: ${{ secrets.EC2_HOST }}
#          username: ${{ secrets.EC2_USERNAME }}
#          key: ${{ secrets.EC2_SSH_KEY }}
#          source: "docker-compose.yml"
#          target: "/api"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd api
            
            cat > .env << EOF
            # Database config
            POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_PORT=${{ vars.POSTGRES_PORT }}
            
            # Spring Boot config
            SPRING_DATASOURCE_URL=jdbc:postgresql://db:${{ vars.POSTGRES_PORT }}/${{ secrets.POSTGRES_DB }}
            SPRING_DATASOURCE_USERNAME=${{ secrets.POSTGRES_USER }}
            SPRING_DATASOURCE_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            
            # Firebase config
            FIREBASE_PROJECT_ID=${{ vars.FIREBASE_PROJECT_ID }}
            FIREBASE_ISSUER=https://securetoken.google.com/${{ vars.FIREBASE_PROJECT_ID }}
            FIREBASE_JWK_URI=https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
            FIREBASE_AUDIENCE=${{ vars.FIREBASE_PROJECT_ID }}
            
            # Docker image for deployment
            DOCKER_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPO }}:${{ github.sha }}
            EOF
            
            chmod 600 .env
            
            cat > docker-compose.yml << 'EOL'
            services:
              db:
                image: postgres:16-alpine
                container_name: db
                restart: unless-stopped
                env_file: .env
                environment:
                  POSTGRES_DB: ${POSTGRES_DB}
                  POSTGRES_USER: ${POSTGRES_USER}
                  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
                ports:
                  - "${POSTGRES_PORT}:5432"
                volumes:
                  - postgres_data:/var/lib/postgresql/data
                healthcheck:
                  test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
                  interval: 10s
                  timeout: 5s
                  retries: 5
            
              # Api image will be pulled, not built in the ec2 instance. For local dev, build the image beforehand with the local-dev tag
              api:
                image: ${DOCKER_IMAGE:-local-dev}
                container_name: api
                depends_on:
                  db:
                    condition: service_healthy
                env_file: .env
                ports:
                  - "8080:8080"
                environment:
                  SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
                  SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
                  SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
                  FIREBASE_ISSUER: ${FIREBASE_ISSUER}
                  FIREBASE_JWK_URI: ${FIREBASE_JWK_URI}
                  FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
                restart: unless-stopped

            volumes:
              postgres_data:
                driver: local
            EOL
            
            docker-compose pull
            docker-compose up -d